function mexCompile
% function mexCompile
% 
% Compile VOISE mex files from C++ source code written by Jack Scantlebury
% for his MSc thesis at UCL entitled "The SKIZ Operator and VOISE Algorithm
% for Image Segmentation by Voronoi Diagrams" in 2018.

%
% $Id: mexCompile.m,v 1.1 2020/05/03 10:55:20 patrick Exp $
%
% Copyright (c) 2020 Patrick Guio <patrick.guio@gmail.com>
% All Rights Reserved.
%
% This program is free software; you can redistribute it and/or modify it
% under the terms of the GNU General Public License as published by the
% Free Software Foundation; either version 3 of the License, or (at your
% option) any later version.
%
% This program is distributed in the hope that it will be useful, but
% WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
% Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <http://www.gnu.org/licenses/>.

root = '../cpp/';
gopts = {'-R2018a','COMPTIMFLAGS="-O3"'};%,'CXXFLAGS="\$CXXFLAGS -Wall"'};
popts = {'CXXFLAGS="\$CXXFLAGS -fopenmp"','LDFLAGS="\$LDFLAGS -fopenmp"'};

files = {[root 'mex/addSeedToVDBatch.cpp'],...
         [root 'aux-functions/proposition2.cpp'],...
				 [root 'mex/pushVD.cpp'],...
				 [root 'mex/grabVD.cpp'],...
				 [root 'skizException.cpp'],...
				 [root 'addSeed.cpp'],...
				 [root 'pointInRegion.cpp'],...
				 [root 'NSStar.cpp'],...
				 [root 'vd.cpp'],...
				 [root 'getRegion.cpp']};
mex(files{:},gopts{:});

files = {[root 'mex/sopToWop.cpp'],...
         [root 'mex/grabVD.cpp'],...
				 [root 'vd.cpp'],...
				 [root 'getRegion.cpp']};
mex(files{:},gopts{:});

files = {[root 'mex/getCentroidSeedBatch.cpp'],...
         [root 'mex/grabVD.cpp'],...
         [root 'vd.cpp'],...
         [root 'getRegion.cpp'],...
				 [root 'mex/grabW.cpp'],...
				 [root 'getCentroid.cpp']};
mex(files{:},gopts{:});

files = {[root 'mex/getVDOpBatch.cpp'],...
         [root 'mex/pushVD.cpp'],...
				 [root 'mex/grabVD.cpp'],...
         [root 'skizException.cpp'],...
				 [root 'vd.cpp'],...
         [root 'getRegion.cpp'],...
				 [root 'mex/grabW.cpp'],...
         [root 'aux-functions/metrics.cpp'],...
				 [root 'getOp.cpp']};
mex(files{:},gopts{:},popts{:});

files = {[root 'mex/removeSeedFromVDBatch.cpp'],...
         [root 'mex/pushVD.cpp'],...
         [root 'mex/grabVD.cpp'],...
         [root 'skizException.cpp'],...
         [root 'removeSeed.cpp'], ...
				 [root 'pointInRegion.cpp'],...
				 [root 'vd.cpp'],...
         [root 'getRegion.cpp']};
mex(files{:},gopts{:});


files = {[root 'mex/addSeedToVD.cpp'],...
         [root 'aux-functions/proposition2.cpp'],...
				 [root 'mex/pushVD.cpp'],...
         [root 'mex/grabVD.cpp'],...
         [root 'skizException.cpp'],...
         [root 'addSeed.cpp'],...
         [root 'pointInRegion.cpp'],...
         [root 'NSStar.cpp'],...
				 [root 'vd.cpp'],...
         [root 'getRegion.cpp']};
mex(files{:},gopts{:});

files = {[root 'mex/removeSeedFromVD.cpp'],...
         [root 'mex/pushVD.cpp'],...
				 [root 'mex/grabVD.cpp'],...
         [root 'skizException.cpp'],...
				 [root 'removeSeed.cpp'],...
				 [root 'pointInRegion.cpp'],...
         [root 'vd.cpp'],...
				 [root 'getRegion.cpp']};
mex(files{:},gopts{:});


